config/routes.rb
Rails.application.routes.draw do
  resources :endorsements
  resources :affiliates
  resources :pages
  mount ActionCable.server => '/cable'

  devise_for :users

  ActiveAdmin.routes(self)
  
  get 'welcome', to: "welcome#show"
  get "rules", to: "welcome#rules"
  
  get 'confirm_age', to: "welcome#confirm_age"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'homepage#show'

  get '/schedule.json', to: 'schedule#json'

  get "user/:username", to: 'user#show'
  get 'user/:username/edit', to: 'user#edit'
  post 'user/:username/update', to: 'user#update'
  patch 'user/:username/update', to: 'user#update'
  get 'user/:username/update', to: 'user#update'
  
  get '/:slug', to: "pages#show"

end

app/models/affiliate.rb
class Affiliate < ApplicationRecord
end

app/controllers/affiliates_controller.rb
class AffiliatesController < ApplicationController
  load_and_authorize_resource
  before_action :set_affiliate, only: [:show, :edit, :update, :destroy]

  # GET /affiliates
  # GET /affiliates.json
  def index
    @affiliates = Affiliate.all
  end

  # GET /affiliates/1
  # GET /affiliates/1.json
  def show
  end

  # GET /affiliates/new
  def new
    @affiliate = Affiliate.new
  end

  # GET /affiliates/1/edit
  def edit
  end

  # POST /affiliates
  # POST /affiliates.json
  def create
    @affiliate = Affiliate.new(affiliate_params)

    respond_to do |format|
      if @affiliate.save
        format.html { redirect_to @affiliate, notice: 'Affiliate was successfully created.' }
        format.json { render :show, status: :created, location: @affiliate }
      else
        format.html { render :new }
        format.json { render json: @affiliate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /affiliates/1
  # PATCH/PUT /affiliates/1.json
  def update
    respond_to do |format|
      if @affiliate.update(affiliate_params)
        format.html { redirect_to @affiliate, notice: 'Affiliate was successfully updated.' }
        format.json { render :show, status: :ok, location: @affiliate }
      else
        format.html { render :edit }
        format.json { render json: @affiliate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /affiliates/1
  # DELETE /affiliates/1.json
  def destroy
    @affiliate.destroy
    respond_to do |format|
      format.html { redirect_to affiliates_url, notice: 'Affiliate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_affiliate
      @affiliate = Affiliate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def affiliate_params
      params.require(:affiliate).permit(:name, :user_id, :type, :plan, :weight)
    end
end

app/views/affiliates/_form.html.erb
<%= form_with(model: affiliate, local: true) do |form| %>
  <% if affiliate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(affiliate.errors.count, "error") %> prohibited this affiliate from being saved:</h2>

      <ul>
        <% affiliate.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="field">
    <%= form.label :plan %>
    <%= form.text_field :plan %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.text_field :weight %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/affiliates/edit.html.erb
<h1>Editing Affiliate</h1>

<%= render 'form', affiliate: @affiliate %>

<%= link_to 'Show', @affiliate %> |
<%= link_to 'Back', affiliates_path %>

app/views/affiliates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Affiliates</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th>Type</th>
      <th>Plan</th>
      <th>Weight</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @affiliates.each do |affiliate| %>
      <tr>
        <td><%= affiliate.name %></td>
        <td><%= affiliate.user_id %></td>
        <td><%= affiliate.type %></td>
        <td><%= affiliate.plan %></td>
        <td><%= affiliate.weight %></td>
        <td><%= link_to 'Show', affiliate %></td>
        <td><%= link_to 'Edit', edit_affiliate_path(affiliate) %></td>
        <td><%= link_to 'Destroy', affiliate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Affiliate', new_affiliate_path %>

app/views/affiliates/new.html.erb
<h1>New Affiliate</h1>

<%= render 'form', affiliate: @affiliate %>

<%= link_to 'Back', affiliates_path %>

app/views/affiliates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @affiliate.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @affiliate.user_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @affiliate.type %>
</p>

<p>
  <strong>Plan:</strong>
  <%= @affiliate.plan %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @affiliate.weight %>
</p>

<%= link_to 'Edit', edit_affiliate_path(@affiliate) %> |
<%= link_to 'Back', affiliates_path %>