config/routes.rb
Rails.application.routes.draw do
  resources :endorsements
  resources :affiliates
  resources :pages
  mount ActionCable.server => '/cable'

  devise_for :users

  ActiveAdmin.routes(self)
  
  get 'welcome', to: "welcome#show"
  get "rules", to: "welcome#rules"
  
  get 'confirm_age', to: "welcome#confirm_age"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'homepage#show'

  get '/schedule.json', to: 'schedule#json'

  get "user/:username", to: 'user#show'
  get 'user/:username/edit', to: 'user#edit'
  post 'user/:username/update', to: 'user#update'
  patch 'user/:username/update', to: 'user#update'
  get 'user/:username/update', to: 'user#update'
  
  get '/:slug', to: "pages#show"

end

app/models/endorsement.rb
class Endorsement < ApplicationRecord
  has_one_attached :banner
  has_one_attached :logo
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController
  load_and_authorize_resource
  before_action :set_endorsement, only: [:show, :edit, :update, :destroy]

  # GET /endorsements
  # GET /endorsements.json
  def index
    @endorsements = Endorsement.all
  end

  # GET /endorsements/1
  # GET /endorsements/1.json
  def show
  end

  # GET /endorsements/new
  def new
    @endorsement = Endorsement.new
  end

  # GET /endorsements/1/edit
  def edit
  end

  # POST /endorsements
  # POST /endorsements.json
  def create
    @endorsement = Endorsement.new(endorsement_params)

    respond_to do |format|
      if @endorsement.save
        format.html { redirect_to @endorsement, notice: 'Endorsement was successfully created.' }
        format.json { render :show, status: :created, location: @endorsement }
      else
        format.html { render :new }
        format.json { render json: @endorsement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /endorsements/1
  # PATCH/PUT /endorsements/1.json
  def update
    respond_to do |format|
      if @endorsement.update(endorsement_params)
        format.html { redirect_to @endorsement, notice: 'Endorsement was successfully updated.' }
        format.json { render :show, status: :ok, location: @endorsement }
      else
        format.html { render :edit }
        format.json { render json: @endorsement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /endorsements/1
  # DELETE /endorsements/1.json
  def destroy
    @endorsement.destroy
    respond_to do |format|
      format.html { redirect_to endorsements_url, notice: 'Endorsement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_endorsement
      @endorsement = Endorsement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def endorsement_params
      params.require(:endorsement).permit(:affiliate_id, :name, :caption, :enabled, :media_uri, :media_type)
    end
end

app/helpers/endorsement_helper.rb
module EndorsementHelper
  def random_sponsors num
    sponsors = Endorsement.where(enabled: true, endorsement_type: "sponsor")
    num = [num, sponsors.count].min
    sponsors.limit(num).order(Arel.sql('RAND()')) || []
  end

  def premier_sponsors num=3
    get_sponsors('premier',num)
  end
  
  def secondary_sponsors num=4
    get_sponsors('sponsor',num)
  end

  def get_sponsors(sponsor_type, num = 0)
    sponsors = Endorsement.where(enabled: true, endorsement_type: sponsor_type)
    sponsors = sponsors.limit(num) if (num > 0)
    sponsors = sponsors.order(Arel.sql('RAND()')).to_a
    return [] unless sponsors.count > 0
    while sponsors.count < num do
      sponsors << sponsors.first
    end
    return sponsors
  end

  def endorsements_by_type(type,n=nil)
    endorsements = Endorsement.where(enabled: true, endorsement_type: type)
    endorsements = endorsements.limit(n) if n.present?
    endorsements = endorsements.order(Arel.sql('RAND()')) || []
  end

  def cruise_spaces(n=nil)
    endorsements_by_type("cruise",n)
  end

  def experience_partners(n=nil)
    endorsements_by_type("experience",n)
  end

  def top_banner
    @top_banner ||= (Endorsement.where(enabled: true, endorsement_type: "top").limit(1).order(Arel.sql('RAND()')).first || Endorsement.new)
  end

  def vendors hall
    Endorsement.where(enabled: true, endorsement_type: "vendor-#{hall}").order(Arel.sql('RAND()'))
  end
  
end

app/views/endorsements/_form.html.erb
<%= form_with(model: endorsement, local: true) do |form| %>
  <% if endorsement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(endorsement.errors.count, "error") %> prohibited this endorsement from being saved:</h2>

      <ul>
        <% endorsement.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :affiliate_id %>
    <%= form.text_field :affiliate_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :caption %>
    <%= form.text_field :caption %>
  </div>

  <div class="field">
    <%= form.label :enabled %>
    <%= form.check_box :enabled %>
  </div>

  <div class="field">
    <%= form.label :media_uri %>
    <%= form.text_field :media_uri %>
  </div>

  <div class="field">
    <%= form.label :media_type %>
    <%= form.text_field :media_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/endorsements/edit.html.erb
<h1>Editing Endorsement</h1>

<%= render 'form', endorsement: @endorsement %>

<%= link_to 'Show', @endorsement %> |
<%= link_to 'Back', endorsements_path %>

app/views/endorsements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Endorsements</h1>

<table>
  <thead>
    <tr>
      <th>Affiliate</th>
      <th>Name</th>
      <th>Caption</th>
      <th>Enabled</th>
      <th>Media uri</th>
      <th>Media type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @endorsements.each do |endorsement| %>
      <tr>
        <td><%= endorsement.affiliate_id %></td>
        <td><%= endorsement.name %></td>
        <td><%= endorsement.caption %></td>
        <td><%= endorsement.enabled %></td>
        <td><%= endorsement.media_uri %></td>
        <td><%= endorsement.media_type %></td>
        <td><%= link_to 'Show', endorsement %></td>
        <td><%= link_to 'Edit', edit_endorsement_path(endorsement) %></td>
        <td><%= link_to 'Destroy', endorsement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Endorsement', new_endorsement_path %>

app/views/endorsements/new.html.erb
<h1>New Endorsement</h1>

<%= render 'form', endorsement: @endorsement %>

<%= link_to 'Back', endorsements_path %>

app/views/endorsements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Affiliate:</strong>
  <%= @endorsement.affiliate_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @endorsement.name %>
</p>

<p>
  <strong>Caption:</strong>
  <%= @endorsement.caption %>
</p>

<p>
  <strong>Enabled:</strong>
  <%= @endorsement.enabled %>
</p>

<p>
  <strong>Media uri:</strong>
  <%= @endorsement.media_uri %>
</p>

<p>
  <strong>Media type:</strong>
  <%= @endorsement.media_type %>
</p>

<%= link_to 'Edit', edit_endorsement_path(@endorsement) %> |
<%= link_to 'Back', endorsements_path %>